version: "3"

services:
  db:
    image: mariadb:latest
    container_name: nycu_qs
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./dbdata:/var/lib/mysql
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
